name: Bundle sources
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: recursive
    - name: Setup
      run: |
        ./bootstrap.sh
        ./b2 tools/boostdep/build
    - name: Package
      run: |
        ./package_shards
        sha256sum output/output.7z
    - name: Make release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "output/output.7z"
        token: ${{secrets.GITHUB_TOKEN}}